create table type1user(
                          user_id int primary key generated BY DEFAULT AS IDENTITY,
                          name varchar not null,
                          password varchar not null
);
create table article(
                        article_id int primary key generated BY DEFAULT AS IDENTITY,
                        title varchar(100),
                        text varchar,
                        current_likes int check ( current_likes >= 0 ),
                        creation_time timestamp,
                        author_user_id int references type1user(user_id) on delete CASCADE
);
create table comment(
                        comment_id int primary key generated by default as IDENTITY,
                        text varchar,
                        article_id int references article(article_id) on delete CASCADE,
                        likes_count int check( likes_count >= 0 ),
                        creation_time timestamp,
                        author_user_id int references type1user(user_id) on delete CASCADE
);